rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - rbx-2
before_script:
  - gem install hoe
  - gem install rake-compiler
  - gem install minitest -v '~> 5.0'
script: rake test
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
